name: unit test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm ci
        run: npm ci
      - name: npm run test:lint
        run: npm run test:lint
      - name: npm run test:unit
        run: npm run test:unit
      - name: npm run test:unit:coverage
        if: matrix.node_version == 14 && matrix.os == 'ubuntu-latest'
        run: npm run test:unit:coverage
      - name: Upload coverage to Codecov
        if: matrix.node_version == 14 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
